export const settings = [
  "-",
  "Fantasy",
  "Medieval",
  "Sci-fi",
  "Space",
  "Cyberpunk",
  "Steampunk",
  "Noir",
  "Wild West",
  "Eldritch",
  "Pirate",
  "Superhero",
  "Post-apocalypse",
  "Zombie",
  "Underwater",
  "Desert",
  "Ancient",
  "Future",
  "Dystopian",
  "Modern",
  "Gangster",
] as const;

export type Setting = (typeof settings)[number];
